lots of refactoring and added the unlink command

diff --git a/nostalgic b/nostalgic
--- a/nostalgic
+++ b/nostalgic
@@ -2,7 +2,7 @@
 
 # ** The MIT License **
 #
-# Copyright (c) 2012 Eric Davis (aka Insanum)
+# Copyright (c) 2012-2025 Eric Davis
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -22,12 +22,12 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 #
-# Dude... just buy me a beer. :-)
-
-#
 # Home: https://github.com/insanum/nostalgic
 #
 # Author: Eric Davis <http://insanum.com>
+# My dotfiles: https://github.com/insanum/dotfiles
+#
+# Dude... just buy me a beer. :-)
 #
 
 REPOS=$HOME/dots
@@ -37,244 +37,281 @@ SKIP_CONFLICTS=0
 FIX_CONFLICTS=0
 PREFIXED=0
 
-CLR_CLEAR="\e[0m"
-CLR_CYAN="\e[1;36m"
-CLR_RED="\e[1;31m"
-CLR_BLUE="\e[1;34m"
-CLR_YELLOW="\e[1;33m"
-CLR_GREEN="\e[1;32m"
-CLR_MAGENTA="\e[1;35m"
+function log_red()     { echo -e "\e[1;31m$*\e[0m"; }
+function log_green()   { echo -e "\e[1;32m$*\e[0m"; }
+function log_yellow()  { echo -e "\e[1;33m$*\e[0m"; }
+function log_blue()    { echo -e "\e[1;34m$*\e[0m"; }
+function log_magenta() { echo -e "\e[1;35m$*\e[0m"; }
+function log_cyan()    { echo -e "\e[1;36m$*\e[0m"; }
 
 function err()
 {
-    echo -e "${CLR_RED}ERROR: $@${CLR_CLEAR}"
-    exit
+    echo -e "\e[1;31mERROR: $*\e[0m"
+    exit 1
 }
 
-function log()
+# Run a command only if not in dry-run mode
+# $@: command and arguments
+function run()
 {
-    local clr=$1
-    shift
-    echo -e "${clr}${@}${CLR_CLEAR}"
+    [[ $DRYRUN -eq 1 ]] && return 0
+    "$@"
 }
 
-# Get the repo name from an URL
+# Get the repo name from a git URL
+# $1: git URL (e.g. https://github.com/user/repo.git)
 function parse_url()
 {
-    SED=sed
-    if [[ $OSTYPE =~ solaris || $OSTYPE =~ darwin ]]; then
-        SED=gsed
-    fi
-    printf "$1" | $SED -r 's#^.*/([^/.]+)(\.git)?$#\1#'
+    local url="${1%.git}"
+    echo "${url##*/}"
 }
 
-function Clone()
+# Clone a git repository into $REPOS
+# $1: git URI to clone
+function clone()
 {
     [[ -z "$1" ]] && err "clone requires an argument"
 
-    local repo="$REPOS/`parse_url $1`"
+    local repo="$REPOS/$(parse_url "$1")"
     [[ -e "$repo" ]] && err "$repo exists"
 
-    log $CLR_GREEN "--> cloning [$repo]"
-    if [[ $DRYRUN -eq 0 ]]; then
-        git clone "$1" "$repo"
-    fi
+    log_green "--> cloning [$repo]"
+    run git clone "$1" "$repo" || err "failed to clone $1"
 }
 
-function List()
+# List all cloned repositories
+function list()
 {
-    for repo in `ls "$REPOS"`; do
-        local repo="$REPOS/$repo"
+    local found=0
+    for repo in "$REPOS"/*; do
         [[ ! -d "$repo" ]] && continue
-        cd "$repo"
-        log $CLR_GREEN "--> repo [$repo] cloned from [`git config remote.origin.url`]"
-        cd "$OLDPWD"
+        found=1
+        local origin=$(cd "$repo" && git config remote.origin.url 2>/dev/null)
+        log_green "--> repo [$repo] cloned from [$origin]"
     done
+    [[ $found -eq 0 ]] && log_yellow "(no repos found)"
 }
 
-function RepoExists()
+# Check if a directory is a valid git repository
+# $1: repo path
+# $2: operation name (for error message)
+function repo_exists()
 {
-    if [[ ! -d "$1" || ! -d "$1/.git" ]]; then
-        err "could not $2 $1 (repo does not exist)"
-    fi
+    [[ -d "$1" && -d "$1/.git" ]] || err "could not $2 $1 (repo does not exist)"
 }
 
-function PullRepo()
+# Execute a function for a repo or all repos
+# $1: function to call
+# $2: repo name or 'ALL'
+# $3: command name (for error message)
+function for_each_repo()
 {
-    RepoExists "$1" 'pull'
+    local func=$1
+    local arg=$2
+    local cmd=$3
 
-    log $CLR_GREEN "--> git pull for repo [$1]"
-    if [[ $DRYRUN -eq 0 ]]; then
-        cd "$1"
-        git pull
-        cd "$OLDPWD"
-    fi
-}
+    [[ -z "$arg" ]] && err "$cmd requires an argument"
 
-function Pull()
-{
-    [[ -z "$1" ]] && err "pull requires an argument"
-
-    if [[ "$1" == ALL ]]; then
-        for r in `ls "$REPOS"`; do
-            local repo="$REPOS/$r"
+    if [[ "$arg" == ALL ]]; then
+        for repo in "$REPOS"/*; do
             [[ ! -d "$repo" ]] && continue
-            PullRepo "$repo"
+            "$func" "$repo"
         done
     else
-        local repo="$REPOS/$1"
-        PullRepo "$repo"
+        "$func" "$REPOS/$arg"
     fi
 }
 
-function StatusRepo()
+# Ensure a directory exists (create if needed, respects dry-run)
+# $1: directory path
+function ensure_dir()
 {
-    RepoExists "$1" 'status'
-
-    log $CLR_GREEN "--> git status for repo [$1]"
-    cd "$1"
-    git status
-    cd "$OLDPWD"
+    [[ -d "$1" ]] && return
+    [[ $DRYRUN -eq 0 ]] && mkdir -p "$1"
+    log_green "--> mkdir [$1]"
 }
 
-function Status()
+# Git pull for a single repository
+# $1: repo path
+function pull_repo()
 {
-    [[ -z "$1" ]] && err "status requires an argument"
+    repo_exists "$1" 'pull'
+    log_green "--> git pull for repo [$1]"
+    run sh -c "cd '$1' && git pull" || log_red "failed to pull repo [$1]"
+}
 
-    if [[ "$1" == ALL ]]; then
-        for r in `ls "$REPOS"`; do
-            local repo="$REPOS/$r"
-            [[ ! -d "$repo" ]] && continue
-            StatusRepo "$repo"
-        done
-    else
-        local repo="$REPOS/$1"
-        StatusRepo "$repo"
+# Git pull for a repo or all repos
+# $1: repo name or 'ALL'
+function pull()
+{
+    for_each_repo pull_repo "$1" "pull"
+}
+
+# Git status for a single repository
+# $1: repo path
+function status_repo()
+{
+    repo_exists "$1" 'status'
+    log_green "--> git status for repo [$1]"
+    (cd "$1" && git status)
+}
+
+# Git status for a repo or all repos
+# $1: repo name or 'ALL'
+function status()
+{
+    for_each_repo status_repo "$1" "status"
+}
+
+# Create a symlink for a single file, handling conflicts
+# $1: repo path
+# $2: relative file path in repo
+# $3: symlink path in destination
+function process_symlink()
+{
+    local repo=$1 file=$2 slink=$3
+
+    if [[ -e "$slink" ]]; then
+        local current_target=$(readlink "$slink" 2>/dev/null)
+
+        if [[ "$current_target" == "$repo/$file" ]]; then
+            log_cyan "--> [$file] already symlinked"
+            return
+        fi
+
+        if [[ $SKIP_CONFLICTS -eq 1 ]]; then
+            log_yellow "(!) conflict symlink exists for [$file]"
+            return
+        fi
+
+        if [[ $FIX_CONFLICTS -eq 0 ]]; then
+            log_yellow "conflict for [$file] -> [$current_target]"
+            read -p "fix $file? [y/(n)] " fix </dev/tty
+            [[ $fix =~ [Nn] ]] && return
+        else
+            log_yellow "(!) fixing conflict for [$file]"
+        fi
+
+        run rm -f "$slink"
     fi
+
+    ensure_dir "$(dirname "$slink")"
+    run ln -s "$repo/$file" "$slink" || log_red "failed to symlink [$slink]"
+    log_green "--> symlinked [$slink] -> [$repo/$file]"
 }
 
-function SymlinkRepo()
+# Create symlinks for all files in a single repository
+# $1: repo path
+function symlink_repo()
 {
     local repo=$1
-    RepoExists "$repo" 'symlink'
+    repo_exists "$repo" 'symlink'
 
-    cd "$repo"
-
-    log $CLR_MAGENTA "--> symlinking repo [$repo]"
-
-    local prefix="."
-    local find='find * -type f -print'
+    log_magenta "--> symlinking repo [$repo]"
 
     if [[ $PREFIXED -eq 1 ]]; then
-        prefix=""
-        find='find .* -type d -name .git -prune -o
-                      -type d -name .    -prune -o
-                      -type d -name ..   -prune -o
-                      -type f -print'
-    fi
-
-    for file in `$find`; do
-        local slink="$DEST/$prefix$file"
-
-        if [[ -e "$slink" && `readlink "$slink"` == "$repo/$file" ]]; then
-            log $CLR_CYAN "--> [$file] already symlinked"
-            continue
-        fi
-
-        if [[ -e "$slink" ]]; then
-            if [[ $SKIP_CONFLICTS -eq 1 ]]; then
-                log $CLR_YELLOW "(!) conflict symlink exists for [$file]"
-                continue
-            fi
-
-            if [[ $FIX_CONFLICTS -eq 0 ]]; then
-                log $CLR_YELLOW "conflict for [$file] -> [`readlink "$slink"`]"
-                read -p "fix $file? [y/(n)]" fix
-                [[ $fix =~ [Nn] ]] && continue
-            else
-                log $CLR_YELLOW "(!) fixing conflict for [$file]"
-            fi
-
-            [[ $DRYRUN -eq 0 ]] && rm -f "$slink"
-        fi
-
-        local d=`dirname $file`
-        if [[ -n "$d" && "$d" != "." ]]; then
-            d=$DEST/$prefix$d
-            if [[ ! -d "$DEST/$d" ]]; then
-                [[ $DRYRUN -eq 0 ]] && mkdir -p $d
-                log $CLR_GREEN "--> mkdir [$d]"
-            fi
-        fi
-
-        [[ $DRYRUN -eq 0 ]] && ln -s "$repo/$file" "$slink"
-        log $CLR_GREEN "--> symlinked [$slink] -> [$repo/$file]"
-    done
-
-    cd "$OLDPWD"
-}
-
-function Symlink()
-{
-    [[ -z "$1" ]] && err "symlink requires an argument"
-
-    if [[ "$1" == ALL ]]; then
-        for r in `ls "$REPOS"`; do
-            local repo="$REPOS/$r"
-            [[ ! -d "$repo" ]] && continue
-            SymlinkRepo "$repo"
+        find "$repo" -mindepth 1 -name '.git' -prune -o \
+                                 -name '.'    -prune -o \
+                                 -name '..'   -prune -o \
+                                 -name '.*' -type f -print | while read -r fullpath; do
+            local file="${fullpath#$repo/}"
+            local slink="$DEST/$file"
+            process_symlink "$repo" "$file" "$slink"
         done
     else
-        local repo="$REPOS/$1"
-        SymlinkRepo "$repo"
+        find "$repo" -mindepth 1 -name '.git' -prune -o \
+                                 -name '.*'   -prune -o \
+                                 -type f -print | while read -r fullpath; do
+            local file="${fullpath#$repo/}"
+            local slink="$DEST/.$file"
+            process_symlink "$repo" "$file" "$slink"
+        done
     fi
 }
 
-function Track()
+# Create symlinks for a repo or all repos
+# $1: repo name or 'ALL'
+function symlink()
+{
+    for_each_repo symlink_repo "$1" "symlink"
+}
+
+# Check if a symlink is dangling and points to a repo, remove if so
+# $1: symlink path
+# $2: repo path
+function check_and_remove_dangling()
+{
+    local slink=$1 repo=$2
+    local link_target=$(readlink "$slink" 2>/dev/null)
+
+    if [[ "$link_target" == "$repo/"* && ! -e "$link_target" ]]; then
+        log_yellow "--> removing dangling symlink [$slink] -> [$link_target]"
+        run rm -f "$slink"
+        return 0
+    fi
+    return 1
+}
+
+# Remove dangling symlinks that point to a repository
+# $1: file or directory path to check
+# $2: repo name
+function unlink()
+{
+    [[ -z "$1" || -z "$2" ]] && err "unlink requires two arguments"
+
+    local target=$1 repo="$REPOS/$2"
+
+    repo_exists "$repo" 'unlink'
+
+    [[ ! -e "$target" && ! -L "$target" ]] && err "path $target does not exist"
+
+    if [[ -L "$target" && ! -d "$target" ]]; then
+        check_and_remove_dangling "$target" "$repo" || \
+            log_cyan "--> [$target] is not a dangling symlink to repo [$repo]"
+    elif [[ -d "$target" ]]; then
+        log_magenta "--> checking directory [$target] for dangling symlinks to repo [$repo]"
+        find "$target" -type l | while read -r slink; do
+            check_and_remove_dangling "$slink" "$repo"
+        done
+    else
+        log_cyan "--> [$target] is not a symlink"
+    fi
+}
+
+# Add a file to a repo, git add it, and create a symlink
+# $1: file path to track
+# $2: repo name
+function track()
 {
     [[ -z "$1" || -z "$2" ]] && err "track requires two arguments"
 
     local repo="$REPOS/$2"
+    local newfile
+    [[ $PREFIXED -eq 1 ]] && newfile="$repo/$1" || newfile="$repo/${1#.}"
 
-    if [[ $PREFIXED -eq 1 ]]; then
-        local newfile="$repo/${1}"
-    else
-        local newfile="$repo/${1#.}"
-    fi
+    repo_exists "$repo" 'track'
 
-    RepoExists "$repo" 'track'
-
-    [[ ! -e "$1" ]] && err "the file $1 does not exist"
+    [[ ! -e "$1" ]] && err "file $1 does not exist"
 
     if [[ -e "$newfile" ]]; then
-        if [[ $FIX_CONFLICTS -eq 0 ]]; then
-            err "the file [$1] already exists in the repo [$2]"
-        else
-            log $CLR_RED "overwriting [$1] which already exists in the repo [$2]"
-        fi
+        [[ $FIX_CONFLICTS -eq 0 ]] && err "file [$1] already exists in repo [$2]"
+        log_red "overwriting [$1] which already exists in repo [$2]"
     fi
 
-    log $CLR_GREEN "--> adding [$newfile] to repo [$repo]"
-    log $CLR_GREEN "--> symlinked [$newfile] to [$1]"
+    log_green "--> adding [$newfile] to repo [$repo]"
+    log_green "--> symlinked [$1] -> [$newfile]"
 
-    if [[ $DRYRUN -eq 0 ]]; then
-        local tgtdir="`dirname $1`"
-        [[ "$tgtdir" != "." ]] && mkdir -p "$repo/${tgtdir#.}"
+    ensure_dir "$(dirname "$newfile")"
+    run mv -f "$1" "$newfile" || err "failed to move file [$1]"
+    run ln -s "$newfile" "$1" || err "failed to create symlink [$1]"
+    run sh -c "cd '$repo' && git add '${newfile#$repo/}'" || err "failed to git add [$newfile]"
 
-        mv -f "$1" "$newfile"
-        ln -s "$newfile" "$1"
-
-        cd "$repo"
-        git add "${1#.}"
-        cd "$OLDPWD"
-    fi
-
-    Status $2
+    status "$2"
 }
 
-function Usage()
+function usage()
 {
-cat <<EOM
+    cat <<EOM
  Usage: nostalgic [options] <cmd> [args]
 
  Options:
@@ -291,11 +328,13 @@ cat <<EOM
    pull <repo>            git pull for the repo ('ALL' for all repos)
    status <repo>          git status for the repo ('ALL' for all repos)
    symlink <repo>         create symlinks for the repo ('ALL' for all repos)
-   track <file> <repo>    add a file to a repo, git add and symlink the file
+   track <file> <repo>    copy the file to the repo, git add it, and symlink it
+   unlink <path> <repo>   remove dangling symlinks (path can be file or dir)
 EOM
+    exit 1
 }
 
-[[ -x `which git` ]] || err "git not found"
+command -v git >/dev/null 2>&1 || err "git not found"
 
 while getopts "nsfpr:d:" opt; do
     case $opt in
@@ -305,7 +344,7 @@ while getopts "nsfpr:d:" opt; do
         p) PREFIXED=1       ;;
         r) REPOS=$OPTARG    ;;
         d) DEST=$OPTARG     ;;
-        *) break
+        *) usage            ;;
     esac
 done
 
@@ -316,7 +355,7 @@ if [[ "${REPOS:0:1}" != "/" ]]; then
 fi
 
 if [[ ! -d "$REPOS" ]]; then
-    log $CLR_GREEN  "repos dir '$REPOS' does not exist (creating)"
+    log_blue "repos dir '$REPOS' does not exist (creating)"
     mkdir -p "$REPOS"
 fi
 
@@ -329,12 +368,13 @@ if [[ ! -d "$DEST" ]]; then
 fi
 
 case $1 in
-    clone)   shift; Clone $@   ;;
-    list)    List              ;;
-    pull)    shift; Pull $@    ;;
-    status)  shift; Status $@  ;;
-    symlink) shift; Symlink $@ ;;
-    track)   shift; Track $@   ;;
-    *)       Usage             ;;
+    clone)   shift; clone "$@"   ;;
+    list)    list                ;;
+    pull)    shift; pull "$@"    ;;
+    status)  shift; status "$@"  ;;
+    symlink) shift; symlink "$@" ;;
+    track)   shift; track "$@"   ;;
+    unlink)  shift; unlink "$@"  ;;
+    *)       usage               ;;
 esac
 
